name: Build and Deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build and Deploy
        run: |
          bundle exec jekyll build
          rm -rf docs
          mv _site/* .
          echo 'yourdomain.com' > CNAME
        env:
          JEKYLL_ENV: production
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

